name: Build Spigot

on:
  workflow_dispatch: # 手动触发
  schedule:
    - cron: '0 0 * * *' # 每天 00:00 UTC 自动触发

jobs:
  build-spigot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install jq for JSON parsing
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Fetch Latest Java Version
        id: fetch-java-version
        run: |
          LATEST_JAVA_VERSION=$(curl -s https://api.adoptium.net/v3/info/available_releases | jq '.most_recent_lts')
          echo "JAVA_VERSION=${LATEST_JAVA_VERSION}" >> $GITHUB_ENV
          echo "Latest Java LTS Version: ${LATEST_JAVA_VERSION}"

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          java-version: ${{ env.JAVA_VERSION }}
          distribution: 'temurin'

      - name: Download BuildTools
        run: |
          curl -o BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar

      - name: Build Spigot
        run: |
          mkdir spigot_build
          mv BuildTools.jar spigot_build/
          cd spigot_build
          java -jar BuildTools.jar --rev latest

      - name: Upload Spigot Jar
        uses: actions/upload-artifact@v4
        with:
          name: spigot-latest
          path: spigot_build/spigot*.jar
